version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - minio
      - keycloak
    volumes:
      - ./src:/app/src

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - ./keycloak:/opt/keycloak/data/import
