version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - minio
    volumes:
      - ./src:/app/src 
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"   
      - "9001:9001"    
    volumes:
      - ./data:/data    
    command: server /data --console-address ":9001"
