version: '3.8'

services:
  web:
    build: . # kazva da se izgradi web service-a ot tekushtata direktoriya (.)
    ports:
      - "8080:8080" # mapva host port 8080 kum container port 8080
    depends_on:
      - db # dependva na db service-a
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data # mountva volume-a db_data kum /var/lib/postgresql/data
      # ako container-a umre, volume-a ostava i ne se trie => se pazqt dannite throungh restarts

volumes: # definira volume-a
  db_data:
